export const FETCH_ROOT = 'FETCH_ROOT';

export const FETCH_OCCUPATIONS = 'FETCH_OCCUPATIONS';
export const FETCH_OCCUPATION = 'FETCH_OCCUPATION';
export const CREATE_OCCUPATION = 'CREATE_OCCUPATION';
export const UPDATE_OCCUPATION = 'UPDATE_OCCUPATION';
export const DELETE_OCCUPATION = 'DELETE_OCCUPATION';

export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';